version: '3'
services:
  db:
    image: mysql:8.0.18
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
    restart: always

  app:
    build:
      context: env/app
    restart: always
    volumes:
      - ./app:/var/www/app

  web:
    build:
      context: env/web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - app
    restart: always

  mta:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    restart: always