version: '3'
services:
  db:
    build:
      context: env/db
    ports:
      - "33060:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=demo
    restart: always

  app:
    build:
      context: env/app
    restart: always
    volumes:
      - ./app:/var/www/app

  app-debug:
    build:
      context: env/app
    command: php -v
    volumes:
      - ./app:/var/www/app
      - ./app-debug/php.ini-development:/usr/local/etc/php/php.ini

  web:
    build:
      context: env/web
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/app
    depends_on:
      - app
    restart: always

  mta:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
    restart: always